#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: hahaya
disqus_show_comment_count: true

# site
title: hahaya's blog
url: http://hahaya.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: hahaya
author_email: hahayacoder@gmail.com
author_info: <a href="http://hahaya.github.com">hahaya</a>
