#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: tanxiaoxian
disqus_show_comment_count: true

# site
title: tanxiaoxian's blog
url: http://tanxiaoxian.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: tanxiaoxian
author_email: tanxiaoxiancoder@gmail.com
author_info: <a href="http://tanxiaoxian.github.com">tanxiaoxian</a>
